services:
  - type: web
    name: fashion-store-app
    env:
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
      - key: SPRING_SQL_INIT_ENCODING
        value: UTF-8
      - key: IMAGE_FOLDER
        value: /app/static/img

  - type: pserv
    name: fashion-store-db
    env:
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: root
