services:

  - type: web
    plan: free
    name: fashion-store-app
    runtime: docker
    region: singapore
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-db:3306/ecdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
      - key: SPRING_SQL_INIT_ENCODING
        value: UTF-8
      - key: IMAGE_FOLDER
        value: /app/static/img
      - key: SERVER_PORT
        value: 8080

  - type: web
    plan: free
    name: mysql-db
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile.sql
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: ecdb
      - key: MYSQL_USER
        value: app_user
      - key: MYSQL_PASSWORD
        value: root
      - key: SERVER_PORT
        value: 3306