services:
  - name: db
    env: 
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: ecdb
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: root
    dockerfilePath: ./Dockerfile.sql
    envVars:
      - key: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "yes"

  - name: app
    env:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://db:3306/ecdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
      - key: SPRING_SQL_INIT_ENCODING
        value: UTF-8
      - key: IMAGE_FOLDER
        value: /app/static/img
    dockerfilePath: ./Dockerfile
