services:
  - type: pserv
    name: mysql-db
    runtime: docker
    dockerfilePath: ./Dockerfile.sql
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: ecdb
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: root
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    dockerCommand: --init-file /initdb/init.sql

  - type: web
    name: fashion-store-app
    runtime: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/your-repo.git # 適切なリポジトリURLを記載
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-db:3306/ecdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
      - key: SPRING_SQL_INIT_ENCODING
        value: UTF-8
      - key: IMAGE_FOLDER
        value: /app/static/img
    disk:
      name: static-img
      mountPath: /app/static/img
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60
    healthCheckPath: /