services:
  - type: web
    plan: free
    name: fashion-store-app
    runtime: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:/data/testdb;DB_CLOSE_DELAY=-1
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: none